### ISSUE TITLE
Pathway UX remarks

### ISSUE THREAD

**Issue by chartgerink** [ubvu/open-handbook#115]
This PR tracks the comments from VU UX regarding the pathway page(s).

- [x] Are there other terms that can be used to summarize the function of this page? Pathways remains vague and does not fully clarify what can be found on this page. (fixed and automated in #149)
- [x] Make sure all images load and are visible. A few are now giving a 404. (fixed over multiple PRs, automated check in #160)
- [x] Provide a clear description below the images that briefly summarizes what can be found on the page (initial texts included in #148)

**Comment by chartgerink** [comment]
In [hackathon 2](https://ubvu.github.io/open-handbook/blog/2024-09-05hackathon.html), a vote indicated "Guides" was the preferred alternative.
